version: '2'
services:
  api_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - db-service
  db_service:
    image: postgres:latest
    container_name: db_service
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGPORT: 5432
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
