version: '2'
services:
  api_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - db_service
  db_service:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    env_file: .env
    volumes:
      - postgres:/data/postgres
