version: '3.7'

services:
  api_service:
    build:
      context: .
      target: api-${NODE_ENV}
    ports:
      - ${SERVER_PORT}:3000
    command: npm start
    depends_on:
      - db_service
    env_file: .env
  db_service:
    image: postgres:12
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}